# Generated by Django 4.0.2 on 2022-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_name',
            field=models.CharField(default='MiliMili小助手', max_length=32, verbose_name='发送者'),
        ),
    ]
