# Generated by Django 4.0.2 on 2022-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0002_message_from_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddField(
            model_name='message',
            name='from_type',
            field=models.IntegerField(default=0, verbose_name='分类'),
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
