# Generated by Django 4.0.2 on 2022-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0003_alter_message_options_message_from_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_name',
        ),
        migrations.AddField(
            model_name='message',
            name='from_id',
            field=models.IntegerField(default=1, verbose_name='发送者id'),
        ),
    ]
