# Generated by Django 4.0.2 on 2022-05-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0004_remove_message_from_name_message_from_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_time'], 'verbose_name': '站内信', 'verbose_name_plural': '站内信列表'},
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
