# Generated by Django 4.0.3 on 2022-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('video_num', models.IntegerField(default=0, verbose_name='视频数')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('fan_num', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('follow_num', models.IntegerField(default=0, verbose_name='关注数')),
                ('avatar_url', models.FileField(upload_to='avatar', verbose_name='用户头像')),
                ('isActive', models.BooleanField(default=False, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站用户',
                'verbose_name_plural': '网站用户列表',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserToFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('fan_id', models.IntegerField(default=0, verbose_name='粉丝')),
            ],
        ),
        migrations.CreateModel(
            name='UserToFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('follow_id', models.IntegerField(default=0, verbose_name='关注的up主')),
            ],
        ),
        migrations.CreateModel(
            name='UserToVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('video_id', models.IntegerField(default=0, verbose_name='收藏的视频')),
            ],
        ),
    ]
