# Generated by Django 4.0.3 on 2022-04-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('video_id', models.IntegerField(default=0, verbose_name='看过的视频')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='isSuperAdmin',
            field=models.BooleanField(default=False, verbose_name='是否为超级管理员'),
        ),
    ]
