# Generated by Django 4.0.3 on 2022-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usertohistory_user_issuperadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='avatar/logo/DefaultAvatar.jpg', max_length=128, verbose_name='用户头像路径'),
        ),
    ]
