# Generated by Django 4.0.3 on 2022-04-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatar/', upload_to='avatar', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='https://milimili.super2021.com/static/avatar/DefaultAvatar.jpg', max_length=128, verbose_name='用户头像路径'),
        ),
    ]
