# Generated by Django 4.0.3 on 2022-04-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_avatar_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='', upload_to='', verbose_name='用户头像'),
        ),
    ]
