# Generated by Django 4.0.3 on 2022-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to='', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='https://global-1309504341.cos.ap-beijing.myqcloud.com/default.jpg', max_length=128, verbose_name='用户头像路径'),
        ),
    ]
