# Generated by Django 4.0.2 on 2022-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usertovideo_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='收获的点赞数'),
        ),
    ]
