# Generated by Django 4.0.2 on 2022-04-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_like_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collect_num',
            field=models.IntegerField(default=0, verbose_name='收获的收藏数'),
        ),
    ]
