# Generated by Django 4.0.2 on 2022-04-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_collect_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_num',
            field=models.IntegerField(default=0, verbose_name='收藏夹数'),
        ),
    ]
