# Generated by Django 4.0.2 on 2022-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_favorite_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complain_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投诉时间'),
        ),
    ]
