# Generated by Django 4.0.2 on 2022-04-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_complain_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('content', models.CharField(default='', max_length=256, verbose_name='搜索的内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
