# Generated by Django 4.0.2 on 2022-05-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_usertosearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='中国大陆', max_length=32, verbose_name='所在地'),
        ),
    ]
