# Generated by Django 4.0.2 on 2022-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='', max_length=32, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=30, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='', max_length=12, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(default='', max_length=256, verbose_name='个人签名'),
        ),
    ]
