# Generated by Django 4.0.2 on 2022-05-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_birthday_user_nickname_user_sex_user_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToComment_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='主体')),
                ('comment_id', models.IntegerField(default=0, verbose_name='点赞的评论')),
            ],
        ),
    ]
