# Generated by Django 4.0.2 on 2022-05-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_usertocomment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='', max_length=128, verbose_name='用户头像路径'),
        ),
    ]
