# Generated by Django 4.0.2 on 2022-05-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_usertovideo_usertovideo_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertovideo_collect',
            name='cnt',
            field=models.IntegerField(default=0, verbose_name='收藏次数'),
        ),
    ]
