# Generated by Django 4.0.2 on 2022-05-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_usertovideo_collect_cnt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToHistory',
        ),
        migrations.AlterField(
            model_name='usertovideo_collect',
            name='cnt',
            field=models.IntegerField(default=1, verbose_name='收藏次数'),
        ),
    ]
