# Generated by Django 4.0.2 on 2022-05-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_usertohistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToHistory',
        ),
    ]
