# Generated by Django 4.0.2 on 2022-06-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_delete_usertohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertocomment_like',
            name='root_id',
            field=models.IntegerField(default=0, verbose_name='点赞的根评论'),
        ),
    ]
