# Generated by Django 4.0.3 on 2022-04-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('video', models.FileField(upload_to='video', verbose_name='视频')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collect_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('view_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频列表',
                'db_table': 'video',
                'ordering': ['-updated_time'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('reply_comment_id', models.IntegerField(default=0, verbose_name='回复评论编号')),
                ('reply_username', models.CharField(default='null', max_length=30, verbose_name='回复评论用户名')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论列表',
                'db_table': 'comment',
                'ordering': ['-created_time'],
            },
        ),
    ]
