# Generated by Django 4.0.3 on 2022-04-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='avatar_url',
            field=models.FileField(default='cover/', upload_to='cover', verbose_name='视频'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag1',
            field=models.CharField(default='', max_length=32, verbose_name='标签1'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag2',
            field=models.CharField(default='', max_length=32, verbose_name='标签2'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag3',
            field=models.CharField(default='', max_length=32, verbose_name='标签3'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag4',
            field=models.CharField(default='', max_length=32, verbose_name='标签4'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag5',
            field=models.CharField(default='', max_length=32, verbose_name='标签5'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.FileField(default='video/', upload_to='video', verbose_name='视频'),
        ),
        migrations.AddField(
            model_name='video',
            name='zone',
            field=models.CharField(default='', max_length=32, verbose_name='专区'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
    ]
