# Generated by Django 4.0.3 on 2022-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_video_video_avatar_url_video_tag1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avatar',
            field=models.FileField(default='cover/', upload_to='cover', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='video/', upload_to='video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='video',
            name='avatar_url',
            field=models.CharField(default='cover/', max_length=128, verbose_name='封面路径'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='video/', max_length=128, verbose_name='视频路径'),
        ),
    ]
