# Generated by Django 4.0.3 on 2022-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_avatar_video_video_alter_video_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='avatar',
            field=models.FileField(default='', upload_to='cover', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='', upload_to='video', verbose_name='视频'),
        ),
    ]
