# Generated by Django 4.0.2 on 2022-04-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_isaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='avatar_url',
            field=models.CharField(default='', max_length=128, verbose_name='封面路径'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='', max_length=128, verbose_name='视频路径'),
        ),
    ]
