# Generated by Django 4.0.2 on 2022-04-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_video_avatar_url_alter_video_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobToVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='', max_length=128, verbose_name='审核编号')),
                ('video_id', models.IntegerField(default=0, verbose_name='视频编号')),
            ],
        ),
    ]
