# Generated by Django 4.0.2 on 2022-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_jobtovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='need_verify',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
