# Generated by Django 4.0.2 on 2022-04-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='isPrivate',
            field=models.IntegerField(default=0, verbose_name='是否为私有'),
        ),
    ]
