# Generated by Django 4.0.2 on 2022-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_alter_favorite_isprivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteToVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_id', models.IntegerField(default=0, verbose_name='收藏夹编号')),
                ('video_id', models.IntegerField(default=0, verbose_name='视频编号')),
            ],
        ),
    ]
