# Generated by Django 4.0.2 on 2022-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_favoritetovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description_token',
            field=models.TextField(default='', verbose_name='描述分词'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_token',
            field=models.CharField(default='', max_length=64, verbose_name='标题分词'),
        ),
    ]
