# Generated by Django 4.0.4 on 2022-04-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_remove_videocomplain_user_videocomplain_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title_token',
        ),
    ]
