# Generated by Django 4.0.4 on 2022-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_remove_video_title_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, verbose_name='审核后的标签')),
            ],
        ),
        migrations.CreateModel(
            name='UnAuditedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, verbose_name='待审核的标签')),
            ],
        ),
    ]
