# Generated by Django 4.0.2 on 2022-04-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_auditedtag_unauditedtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditedTag',
        ),
        migrations.DeleteModel(
            name='UnAuditedTag',
        ),
    ]
