# Generated by Django 4.0.2 on 2022-05-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0022_videocomment_like_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='islike',
            field=models.IntegerField(default=0, verbose_name='是否已点赞'),
        ),
    ]
