# Generated by Django 4.0.4 on 2022-05-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_favorite_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=64, verbose_name='分区名称')),
            ],
        ),
    ]
