# Generated by Django 4.0.2 on 2022-05-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0025_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=256, verbose_name='标题'),
        ),
    ]
