# Generated by Django 4.0.2 on 2022-05-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0026_alter_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocomment',
            old_name='islike',
            new_name='is_like',
        ),
        migrations.AddField(
            model_name='videocomment',
            name='is_own',
            field=models.IntegerField(default=0, verbose_name='是否是可修改的'),
        ),
    ]
