# Generated by Django 4.0.2 on 2022-05-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0028_usertohistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='need_verify',
        ),
    ]
