# Generated by Django 4.0.2 on 2022-05-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0029_remove_video_need_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='root_id',
            field=models.IntegerField(default=0, verbose_name='根编号'),
        ),
    ]
