# Generated by Django 4.0.2 on 2022-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0030_videocomment_root_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='所属用户号'),
        ),
    ]
