# Generated by Django 4.0.2 on 2022-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0032_alter_videocomment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='reply_user_id',
            field=models.IntegerField(default=0, verbose_name='回复评论用户id'),
        ),
    ]
