# Generated by Django 4.0.2 on 2022-06-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0034_bullet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bullet',
            options={'ordering': ['bullet_id']},
        ),
        migrations.RemoveField(
            model_name='bullet',
            name='user',
        ),
        migrations.AddField(
            model_name='bullet',
            name='bullet_id',
            field=models.IntegerField(default=1, verbose_name='弹幕id'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='approach_time',
            field=models.CharField(default='', max_length=64, verbose_name='到达时间'),
        ),
    ]
