# Generated by Django 4.0.2 on 2022-06-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0035_alter_bullet_options_remove_bullet_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bullet',
            old_name='approach_time',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='bullet',
            old_name='content',
            new_name='txt',
        ),
    ]
