# Generated by Django 4.0.2 on 2022-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0036_rename_approach_time_bullet_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='mode',
            field=models.CharField(default='', max_length=16, verbose_name='弹幕显示位置'),
        ),
        migrations.AddField(
            model_name='bullet',
            name='style_color',
            field=models.CharField(default='', max_length=16, verbose_name='弹幕颜色'),
        ),
        migrations.AddField(
            model_name='bullet',
            name='style_fontSize',
            field=models.CharField(default='', max_length=16, verbose_name='弹幕字体'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='start',
            field=models.CharField(default='', max_length=16, verbose_name='到达时间'),
        ),
    ]
