# Generated by Django 4.0.2 on 2022-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0037_bullet_mode_bullet_style_color_bullet_style_fontsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bullet_num',
            field=models.IntegerField(default=0, verbose_name='弹幕量'),
        ),
    ]
